export const ALL_PERMISSIONS = {
    PERMISSIONS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        CREATE: { method: "POST", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        UPDATE: { method: "PATCH", apiPath: '/api/v1/permissions/:id', module: "PERMISSIONS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/permissions/:id', module: "PERMISSIONS" },
    },
    ROLES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/roles', module: "ROLES" },
        CREATE: { method: "POST", apiPath: '/api/v1/roles', module: "ROLES" },
        UPDATE: { method: "PATCH", apiPath: '/api/v1/roles/:id', module: "ROLES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/roles/:id', module: "ROLES" },
    },
    USERS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/users', module: "USERS" },
        CREATE: { method: "POST", apiPath: '/api/v1/users', module: "USERS" },
        UPDATE: { method: "PATCH", apiPath: '/api/v1/users/:id', module: "USERS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/users/:id', module: "USERS" },
    },
    ATTENDANCE: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/attendance/all-attendance', module: "ATTENDANCE" },
        CHECK_IN: { method: "POST", apiPath: '/api/v1/attendance/check-in', module: "ATTENDANCE" },
        CHECK_OUT: { method: "POST", apiPath: '/api/v1/attendance/check-out', module: "ATTENDANCE" },
        GET_TODAY: { method: "GET", apiPath: '/api/v1/attendance/today', module: "ATTENDANCE" },
        GET_MY_ATTENDANCE: { method: "GET", apiPath: '/api/v1/attendance/my-attendance', module: "ATTENDANCE" },
    },
    SHIFTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/shifts', module: "SHIFTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/shifts', module: "SHIFTS" },
        UPDATE: { method: "PATCH", apiPath: '/api/v1/shifts/:id', module: "SHIFTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/shifts/:id', module: "SHIFTS" },
    },
    USER_SHIFTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/user-shifts', module: "USER_SHIFTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/user-shifts', module: "USER_SHIFTS" },
        UPDATE: { method: "PATCH", apiPath: '/api/v1/user-shifts/:id', module: "USER_SHIFTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/user-shifts/:id', module: "USER_SHIFTS" },
    },
    REPORTS: {
        GET_PAGINATE: { method: "POST", apiPath: '/api/v1/reports', module: "REPORTS" },
    },
    REQUESTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/requests', module: "REQUESTS" },
        GET_REMOTE_WORK_PAGINATE: { method: "GET", apiPath: '/api/v1/requests/remote-work', module: "REQUESTS" },
        GET_LEAVE_PAGINATE: { method: "GET", apiPath: '/api/v1/requests/leave', module: "REQUESTS" },
        GET_OVERTIME_PAGINATE: { method: "GET", apiPath: '/api/v1/requests/overtime', module: "REQUESTS" },
        GET_LATE_EARLY_PAGINATE: { method: "GET", apiPath: '/api/v1/requests/late-early', module: "REQUESTS" },
        GET_SHIFT_CHANGE_PAGINATE: { method: "GET", apiPath: '/api/v1/requests/shift-change', module: "REQUESTS" },
        CREATE_REMOTE_WORK: { method: "POST", apiPath: '/api/v1/requests/remote-work', module: "REQUESTS" },
        CREATE_LEAVE: { method: "POST", apiPath: '/api/v1/requests/leave', module: "REQUESTS" },
        CREATE_OVERTIME: { method: "POST", apiPath: '/api/v1/requests/overtime', module: "REQUESTS" },
        CREATE_LATE_EARLY: { method: "POST", apiPath: '/api/v1/requests/late-early', module: "REQUESTS" },
        CREATE_SHIFT_CHANGE: { method: "POST", apiPath: '/api/v1/requests/shift-change', module: "REQUESTS" },
        UPDATE_REMOTE_WORK: { method: "PATCH", apiPath: '/api/v1/requests/remote-work/:id', module: "REQUESTS" },
        UPDATE_LEAVE: { method: "PATCH", apiPath: '/api/v1/requests/leave/:id', module: "REQUESTS" },
        UPDATE_OVERTIME: { method: "PATCH", apiPath: '/api/v1/requests/overtime/:id', module: "REQUESTS" },
        UPDATE_LATE_EARLY: { method: "PATCH", apiPath: '/api/v1/requests/late-early/:id', module: "REQUESTS" },
    },
    SALARIES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/salary', module: "SALARIES" },
        GET_MY_SALARY: { method: "GET", apiPath: '/api/v1/salary/my-salary', module: "SALARIES" },
        CREATE_SALARY: { method: "POST", apiPath: '/api/v1/salary', module: "SALARIES" },
        CREATE_SALARY_FOR_ALL: { method: "POST", apiPath: '/api/v1/salary/all', module: "SALARIES" },
        UPDATE_SALARY_STATUS: { method: "PATCH", apiPath: '/api/v1/salary/:id/status', module: "SALARIES" },
        UPDATE_SALARY: { method: "PATCH", apiPath: '/api/v1/salary/:id', module: "SALARIES" },
        DELETE_SALARY: { method: "DELETE", apiPath: '/api/v1/salary/:id', module: "SALARIES" },
    },
    DEPARTMENTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/departments', module: "DEPARTMENTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/departments', module: "DEPARTMENTS" },
        UPDATE: { method: "PATCH", apiPath: '/api/v1/departments/:id', module: "DEPARTMENTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/departments/:id', module: "DEPARTMENTS" },
    },
    COMPANIES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/companies', module: "COMPANIES" },
        CREATE: { method: "POST", apiPath: '/api/v1/companies', module: "COMPANIES" },
        UPDATE: { method: "PATCH", apiPath: '/api/v1/companies/:id', module: "COMPANIES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/companies/:id', module: "COMPANIES" },
    },
}

export const ALL_MODULES = {
    AUTH: 'AUTH',
    FILES: 'FILES',
    PERMISSIONS: 'PERMISSIONS',
    ROLES: 'ROLES',
    USERS: 'USERS',
    ATTENDANCE: 'ATTENDANCE',
    SHIFTS: 'SHIFTS',
    USER_SHIFTS: 'USER_SHIFTS',
    REPORTS: 'REPORTS',
    REQUESTS: 'REQUESTS',
    SALARIES: 'SALARIES',
    DEPARTMENTS: 'DEPARTMENTS',
    COMPANIES: 'COMPANIES',
}
